


import type { Metadata } from "next";

import { Dancing_Script } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const dancingScript = Dancing_Script({
  variable: "--font-dancing-script",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // tùy chọn
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={`${dancingScript.variable} antialiased`}
      >
         <Toaster position="top-center"  richColors />
        {children}
      </body>
    </html>
  );
}
